-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_TREE AS TREE
LEFT JOIN ITEM_INFO AS INFO
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE TREE.ITEM_ID NOT IN (SELECT COALESCE(PARENT_ITEM_ID, 0) FROM ITEM_TREE GROUP BY PARENT_ITEM_ID)
ORDER BY TREE.ITEM_ID DESC
;
