-- 코드를 작성해주세요
SELECT SUM(GRADE.SCORE) AS SCORE, GRADE.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_GRADE AS GRADE
JOIN HR_EMPLOYEES AS EMP
ON GRADE.EMP_NO = EMP.EMP_NO
GROUP BY GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
;