-- 코드를 작성해주세요
SELECT DEP.DEPT_ID, DEP.DEPT_NAME_EN, ROUND(AVG(EMP.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES AS EMP
JOIN HR_DEPARTMENT AS DEP
ON DEP.DEPT_ID = EMP.DEPT_ID
GROUP BY DEP.DEPT_ID
ORDER BY AVG_SAL DESC
;